src/librehatti/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from .reports.register_generator import GenerateRegister
from .reports.search import SearchResult
from ajax_select import urls as ajax_select_urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'librehatti.catalog.views.index'),
    url(r'^catalog/', include('librehatti.catalog.urls')),
    url(r'^useraccounts/', include('useraccounts.urls')),
    url(r'^print/', include('librehatti.prints.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/','librehatti.reports.views.search_form'),
    url(r'^search_result/', SearchResult.as_view()),
    url(r'^save_fields', 'librehatti.reports.views.save_fields'),
    url(r'^list_saved_registers', 'librehatti.reports.views.list_saved_registers'),
    url(r'daily_result', 'librehatti.reports.register.daily_report_result', name='daily_report_result'),
    url(r'consultancy_funds_report', 'librehatti.reports.register.consultancy_funds_report', name='consultancy_funds_report'),    
    url(r'tds_report', 'librehatti.reports.register.tds_report_result', name='tds_report_result'),    
    url(r'payment_report', 'librehatti.reports.register.payment_register', name='payment_register'),
    url(r'suspense_clearance_register', 'librehatti.reports.register.suspense_clearance_register'),
    url(r'servicetax', 'librehatti.reports.register.servicetax_register'),
    url(r'^main_register', 'librehatti.reports.register.main_register', name='main_register'),
    url(r'^proforma_register', 'librehatti.reports.register.proforma_register'),
    url(r'^non_payment_register', 'librehatti.reports.register.non_payment_register'),
    url(r'^client_register', 'librehatti.reports.register.client_register', name='client_register'),
    url(r'^material_report', 'librehatti.reports.register.material_report'),
    url(r'^lab_report', 'librehatti.reports.register.lab_report'),
    url(r'^suspense_register', 'librehatti.reports.register.suspense_register'),
    url(r'^registered_users', 'librehatti.reports.register.registered_users'),
    url(r'^filter_sub_category/', 'librehatti.reports.views.filter_sub_category'),
    url(r'^bill/', 'librehatti.prints.views.bill'),
    url(r'^suspense_bill/', 'librehatti.prints.views.suspense_bill'),
#    url(r'^quoted_bill/', 'librehatti.prints.views.quoted_bill'),
    url(r'^tax/', 'librehatti.prints.views.tax'),
    url(r'^bills/', include('librehatti.bills.urls')),
    url(r'^suspense/', include('librehatti.suspense.urls')),
    url(r'^generate_register/', GenerateRegister.as_view(), name='view_register'),
    url(r'^history/','librehatti.reports.previous_history.history'),
    url(r'^details/','librehatti.reports.previous_history.details'),
    url(r'^proforma_details/','librehatti.reports.previous_history.proforma_details'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^voucher/', include('librehatti.voucher.urls')),
    url(r'^receipt/', 'librehatti.prints.views.receipt'),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^programmeletter/', 'librehatti.programmeletter.views.programmeletter'),
    url(r'pending_clearance_register', 'librehatti.reports.register.pending_clearance_register'),
    url(r'tada_register', 'librehatti.reports.register.tada_register'),
    url(r'tada_othercharges_register', 'librehatti.reports.register.tada_othercharges_register'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urls.py
from django.conf.urls.defaults import *
from django.views.generic import TemplateView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^$', 'django.contrib.auth.views.login',
		    { 'template_name': 'index.html'}, ),
    (r'^hello', TemplateView,
                    { 'template': 'job_ok.html' }, ),
    (r'^tcc/', include('ofau.tcc.urls')),
    (r'^report/', include('ofau.report.urls')),
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    (r'^accounts/', include('registration.urls')),
   
)

tcc/models.py
"""
%% models.py %%
This file contains all the defination for models of Automation software. 
including tables, classes, forms and mappers.
"""

#::::::::::::::IMPORT THE HEADER FILE HERE:::::::::::::::::::::::::::#
from django.db import models
from django.forms import ModelForm, TextInput, ModelChoiceField
from django import forms
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db.models import Max ,Q, Sum
import datetime
from django.forms.fields import DateField, ChoiceField, MultipleChoiceField
from tagging.fields import TagField
from tagging.models import Tag
from ofau.tcc.choices import *
#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::#

#::::::::::::::::::::::DEFINE THE MODELS HERE::::::::::::::::::::::::#
class Report(models.Model):
	"""
	** Report **

	Report Class to reterive any Report Information,
	when we fill Job Number and type of Report Store in Database

	"""

	name = models.CharField(max_length=50)

	def __unicode__(self):
        	return self.name

class UserProfile(models.Model):
	"""
	** UserProfile **
	
	UserProfile Class define all field required to submit detail about 
	new Client.

	""" 
    # This field is required.
	user = models.ForeignKey(User)
	first_name = models.CharField(max_length=100)
	middle_name = models.CharField(max_length=100,blank=True, null=True)
	last_name = models.CharField(max_length=100,blank=True, null=True)
	address = models.CharField(max_length=255,blank=True, null=True)
	company = models.CharField(max_length=255,blank=True, null=True)
	city = models.CharField(blank=True,max_length=255, null=True)
	pin_code = models.IntegerField(blank=True,null=True)
	state = models.CharField(max_length=30,choices=STATES_CHOICES,
	default='Punjab')
	website = models.URLField(blank=True, null=True)
	email_address = models.EmailField(max_length=70, blank=True, null=True)
	contact_no = models.CharField(max_length=500)
	type_of_organisation = models.CharField(max_length=20, choices = 
	ORGANISATION_CHOICES)
	date = models.DateField(auto_now_add=True)

	def __unicode__(self):
        	return self.first_name
        	
class Soundexsearch(models.Model):    # Added.....
	"""
	** Soundexsearch **
	
	Soundexsearch class defines all the fields required in soundex search. 
	Its a separate class that handles soundex codes.
	
	"""
	soundex_fname = models.CharField(max_length=100)
	soundex_mname = models.CharField(max_length=100,blank=True, null=True)
	soundex_lname = models.CharField(max_length=100,blank=True, null=True)
	soundex_address = models.CharField(max_length=255,blank=True, null=True)
	soundex_company = models.CharField(max_length=255,blank=True, null=True)
	soundex_city = models.CharField(blank=True,max_length=255, null=True)

class CodeTable(models.Model): #"K" To implement phonetic search for company names
	"""
	** Soundexsearch **
	
	CodeTable class defines the soundex codes for all the
	words contained in database.
	
	"""	
	word = models.CharField(max_length=100)
	code = models.CharField(max_length=100)
	def __unicode__(self):
        	return self.word

class UserProfileForm(ModelForm):
	"""
	** UserProfileForm **
	
	UserProfileForm Class define the form for UserProfile model.
	
	""" 
	class Meta :
		model = UserProfile
		exclude= ['user']
		widgets = {
		'first_name' : TextInput(attrs={'size':60}),
		'middle_name' : TextInput(attrs={'size':60}),
		'last_name' : TextInput(attrs={'size':60}),
		'address' : TextInput(attrs={'size':60}),
		'company' : TextInput(attrs={'size':60}),
		'city' : TextInput(attrs={'size':60}),
		'pin_code' : TextInput(attrs={'size':60}),
		'website' : TextInput(attrs={'size':60}),
		'email_address' : TextInput(attrs={'size':60}),
		'contact_no' : TextInput(attrs={'size':60}),
                  }
	
class Organisation(models.Model):
	"""
	** Organisation **
	
	Organisation Class define all fields required to submit detail 
	about Organisation.
	
	""" 
	name = models.CharField(max_length=50)
	address = models.CharField(max_length=150)
	phone = models.CharField(max_length=20)
	director = models.CharField(max_length=50) 
	status = models.CharField(max_length=5000)
	logo_upload = models.ImageField(upload_to='logo')

	def __unicode__(self):
        	return self.name


class Department(models.Model):
	"""
	** Department **
	
	Department Class define all fields required to submit detail about a 
	department for a particular Organisation.
	
	""" 
	organisation = models.ForeignKey(Organisation)
	name = models.CharField(max_length=50)
	address = models.CharField(max_length=150)
	phone = models.CharField(max_length=20, blank=True)
	dean = models.CharField(max_length=50, blank=True)
	faxno = models.CharField(max_length=100, blank=True)
	email_1 = models.CharField(max_length=75,blank=True)
	email_2 = models.CharField(max_length=75,blank=True)
	url = models.CharField(max_length=50,blank=True)
	about = models.CharField(max_length=150,blank=True)

	def __unicode__(self):
        	return self.name


class Distribution(models.Model):
	"""
	** Distribution **
	
	Distribution Class define all didtribution of income that is to be 
	done.
	
	"""
	name = models.CharField(max_length=100)

	def __unicode__(self):
        	return self.name

 
class Lab(models.Model):
	"""
	** Lab **
	
	Lab Class define all fields required to submit detail about a LAB 
	of a Department.
	
	""" 
	name = models.CharField(max_length=300)
	department = models.ForeignKey(Department)
	tags = TagField()

	def __unicode__(self):
        	return self.name

	def get_tags(self):
        	return Tag.objects.get_for_object(self) 


class MatComment(models.Model):
    name = models.CharField(max_length=300)
    
    def __unicode__(self):
        	return self.name


class Material(models.Model):
	"""
	** Material **
	
	Material Class define all fields required to submit detail about a 
	Material under a Lab.
	
	""" 
	lab = models.ForeignKey(Lab)
	distribution = models.ForeignKey(Distribution)
	name = models.CharField(max_length=300)
	matcomment= models.ForeignKey(MatComment)
	tags = TagField()
	report = models.ForeignKey(Report)
	image = models.ImageField(upload_to='logo', blank='True', null='True')

	def __unicode__(self):
        	return self.name

	def get_tags(self):
        	return Tag.objects.get_for_object(self) 
        	


class Test(models.Model):
	"""
	** Test **
	
	Test Class define all fields required to submit detail about a 
	test under a Material.
	
	""" 
	material = models.ForeignKey(Material)
	name = models.CharField(max_length=300)
	quantity = models.IntegerField(blank=True, null=True)
	unit = models.CharField(max_length=15)
	cost = models.IntegerField(blank=True, null=True)
	tags = TagField()

	def __unicode__(self):
        	return self.name
	
	def get_tags(self):
        	return Tag.objects.get_for_object(self) 


class Clientadd(models.Model):
	"""
	** Clientadd **
	
	Clientadd Class define that which user for which client is adding 
	the jobid.
	
	""" 
	user = models.ForeignKey(User)
	client = models.ForeignKey(UserProfile)
	job_no = models.IntegerField(blank=True, null=True)
	
	
class editClientadd(models.Model):
	"""
	** editClientadd **
	
	editClientadd Class define that which user for which client is 
	adding the performa jobid.
	
	""" 
	user = models.ForeignKey(User)
	client = models.ForeignKey(UserProfile)


class Govt(models.Model):
	"""
	** Govt **
	
	Govt Class define all fields required to submit detail about a 
	organisation Type (Government, Semi-Government or Private).

	""" 
	name =	models.CharField(max_length=600, blank=True )

	def __unicode__(self):
        	return self.name


class Payment(models.Model):
	"""
	** Payment **
	
	Payment Class define all fields required to submit detail about 
	Payment type (Cash, Cheque, Online or DD).
	
	""" 
	name = models.CharField(max_length = 50,blank =True)

	def __unicode__(self):
        	return self.name


class Job(models.Model):
	"""
	**Job**
	
	Job Class is define all field required to submit detail about new 
	Job.
	
	""" 
	client = models.ForeignKey(Clientadd)
	job_no = models.IntegerField(editable =False)
	sample = models.IntegerField()
	ip = models.CharField(max_length=50)
	site = models.CharField(max_length=5000,blank=True,null=True)
	type_of_work = models.ForeignKey(Govt)
	report_type = models.ForeignKey(Report)
	pay = models.CharField(max_length=600)
	check_number = models.CharField(max_length=15,blank=True)
	check_dd_date = models.CharField(blank=True, max_length=15)
	date = models.DateField(auto_now_add=True)
	letter_no = models.CharField(max_length=400,blank=True)
	letter_date = models.DateField( blank=True, null=True)
	tds = models.IntegerField(default="0")
	discount = models.IntegerField(default="0")

	def __unicode__(self):
          return self.id()


class NonPaymentJob(models.Model):
	job_no = models.IntegerField(editable =False)
	client = models.ForeignKey(UserProfile)
	ref_no =  models.CharField(max_length=400,blank=True)
	dated = models.DateField( blank=True, null=True)
	site = models.CharField(max_length=5000,blank=True,null=True)
	material_type = models.CharField(max_length=500)
	date = models.DateField(auto_now_add=True)

	def __unicode__(self):
          return self.id()


class NonPaymentJobForm(forms.ModelForm):
	"""
	** NonPaymentJobForm **
	
	NonPaymentJobForm Class define form for NonPaymentJob model.
	
	""" 
	class Meta :
		model = NonPaymentJob
		exclude= ['date','client']


class EditJob(models.Model):
	"""
	**EditJob**
	
	EditJob Class is define all field required to submit detail about 
	new performa Job.
	
	""" 
	client = models.ForeignKey(editClientadd)
	job_no = models.IntegerField(editable =False)
	sample = models.CharField(max_length=11, default="1")
	ip = models.CharField(max_length=50)
	site = models.CharField(max_length=600,blank=True,null=True)
	type_of_work = models.ForeignKey(Govt)
	report_type = models.ForeignKey(Report)

tcc/forms.py
"""
%% forms.py %%

This file contain the defination of the forms of Automation Software 
"""

from django import forms
from ofau.tcc.models import *

class SuspenceClearence(forms.Form):
	"""
	**SuspenceClearance**

	Suspence Clearence Form for adding extra Charges like labour, car taxi, boring charge, etc.
	"""
	
	labour_charge = forms.IntegerField(initial= '0')
	car_taxi_charge = forms.IntegerField(initial= '0')
	boring_charge_external = forms.IntegerField(initial= '0')
	boring_charge_internal = forms.IntegerField(initial= 0)
	lab_testing_staff = forms.CharField(max_length = 20)
	field_testing_staff = forms.CharField(max_length = 20,required=False)

	test_date = forms.CharField(max_length=300,required=False)
	clear_date = forms.CharField()


class ContactForm(forms.Form):
   	subject = forms.CharField(max_length=100)
    	email = forms.EmailField( label='Your e-mail address')
    	message = forms.CharField(widget=forms.Textarea)

class MonthlyReportadd(forms.Form):
	"""
	**MonthlyReportadd**

	Monthly Reportadd Form is for getting the monthly income and taxes of the company and then subtrating the paid taxes from it.
	"""
 
	month = forms.ChoiceField(choices=MONTH_CHOICES)
	year = forms.ChoiceField(choices=YEAR_CHOICES)
	paid_service_tax =forms.IntegerField(initial= '0')
	paid_education_tax =forms.IntegerField(initial= '0')
	paid_higher_education_tax =forms.IntegerField(initial= '0')
	
class DailyReportadd(forms.Form):
	"""
	**DailyReportadd**

	Daily Report Form to retrieve Daily income Information for a specified payment type like cash, cheque, online and Demand Draft.
	"""

        start_date= forms.DateField()
        end_date= forms.DateField()
        type = forms.ChoiceField( choices=DAILY_CHOICES)

class MonthlyReport(forms.Form):
	"""
	**MonthlyReport**

	Montly Report Form to retrieve Montly Tax Information.
	"""

	month = forms.ChoiceField(choices=MONTH_CHOICES)
	year = forms.ChoiceField(choices=YEAR_CHOICES)

class DateReport(forms.Form):
	"""
	**DateReport**

	Date Report Form that displays start and end date and thus helps in retrieving data between this date range.
	"""

	start_date= forms.DateField()
        end_date= forms.DateField()

	def clean_date(self):
        	start_date = self.cleaned_data['start_date']
		end_date = self.cleaned_data['end_date']
        	if start_date > datetime.date.today():
        	    raise forms.ValidationError("The date cannot be in the future!")
        	return date

class GovPriReport(forms.Form):
	"""
	**GovPriReport**

	Governament Private Report is for different Jobs like: Government/Semi_government/Private. 
	"""

	month = forms.ChoiceField(choices=MONTH_CHOICES)
	year = forms.ChoiceField(choices=YEAR_CHOICES)
	type_of_work = models.ForeignKey(Govt)

class CashBook(forms.Form):
	"""
	**CashBook**

	Cash book to manage the money transactions within a specified date range.
	"""

        start_date= forms.DateField()
        end_date= forms.DateField()
	name = forms.CharField(max_length = 100)
	amount_given = forms.CharField(max_length = 100)


	

templates/abase.html
{% load i18n %}
<!doctype html>
<html>
    <head>
        <title>{{title.name}}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="keywords" content="TCC automation - Office automation Software" />
        <meta name="description" content="Office automation Software is a versatile software which changes according to the work that need to be done." />
        <meta http-equiv="content-language" content="en">
        <meta name="author" content="Sandeep Kaur"/>
		
		<link href="{{ LOCAL_URL }}/static/css/css/dropdown/dropdown.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="{{ LOCAL_URL }}/static/css/css/dropdown/themes/nvidia.com/default.advanced.css" media="screen" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="{{ LOCAL_URL }}/static/css2/css/contrib/animate.min.css" type="text/css" media="all" title="Screen" />
        <link rel="stylesheet" href="{{ LOCAL_URL }}/static/css2/css/jquery.smallipop.css" type="text/css" media="all" title="Screen" />
        <link rel="stylesheet" href="{{ LOCAL_URL }}/static/css2/css/screen.css" type="text/css" media="all" title="Screen" />
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
		<script type="text/javascript" src="{{ LOCAL_URL }}/static/calendar/validate.js"></script><script type="text/javascript" src="{{ LOCAL_URL }}/static/calendar/jquery-1.5.min.js"></script><script type="text/javascript" src="{{ LOCAL_URL }}}/static/calendar/jquery-validate/jquery.validate.js"></script><link href="style.css" rel="stylesheet" type="text/css"><link href="{{ LOCAL_URL }}/static/calendar/datepick/smoothness.datepick.css" rel="stylesheet" type="text/css"><script type="text/javascript" src="{{ LOCAL_URL }}/static/calendar/datepick/jquery.datepick.js"></script><script>
  $(document).ready(function(){
    $('#id_date').datepick({dateFormat:'yyyy-mm-dd'});
    $('#id_start_date').datepick({dateFormat:'yyyy-mm-dd'});
    $('#id_end_date').datepick({dateFormat:'yyyy-mm-dd'});
    $('#id_test_date').datepick({dateFormat:'yyyy-mm-dd'});
    $('#id_letter_date').datepick({dateFormat:'yyyy-mm-dd'});
    $('#id_check_dd_date').datepick({dateFormat:'yyyy-mm-dd'});
    $('#id_dated').datepick({dateFormat:'yyyy-mm-dd'});
	
   
  });
  </script> 
    </head>
    <body link="#C0C0C0" vlink="#808080" alink="#76B900" text="black">
<div>
   {% block header %}
	{% if user.is_authenticated %}<a href="/automation/tcc/index/">{% else %}<a href ="/automation">{% endif %}{% trans "Home" %}</a> | 

	{% if user.is_authenticated %}
	<font color="white">{% trans "Logged in" %}: {{ user.username }} </font>
	(<a href="{% url auth_logout %}">{% trans "Log out" %}</a> | 
	<a href="{% url auth_password_change %}">{% trans "Change password" %}</a>)
	{% else %}
	<a href="{% url auth_login %}">{% trans "Log in" %}</a>
	{% endif %}
	
        {% endblock %}
    </div>
<div class="wrapper">

	<div class="container">

   {% block nav-main %}
	
          <div class="pageHeader hasShadow">
			<h1 ><span class="firstname">{{ title.name }}<span class="sz">{{ title.middle_name }}</span></span><span class="nbsp">&nbsp;</span><span class="lastname"><span class="sz">{{ title.middle_name }}</span>  {{ title.last_name }}</span></h1>
		<h2>
               {{ address }}</h2>
            <br/>

           
				<div class="horizontal-centering"><div><div>

			<ul class="dropdown dropdown-horizontal">
				<li><a href="/automation/tcc/index">Home</a></li>
				<li><a href="/automation/tcc/catalog">Catalog</a></li>
				<li><a href="#" class="dir">Client</a>
					<ul>
						<li><a href="/automation/tcc/addprofile">Register Client</a></li>
						<li><a href="/automation/tcc/search">Search Client</a></li>
						
					</ul>
				</li>
				
				<li><a href="#" class="dir">Register</a>
					<ul>
						<li><a href="/automation/tcc/clientreport">Client Report</a></li>
						<li><a href="/automation/tcc/monthlyreport">Monthly Report</a></li>
						<li><a href="/automation/tcc/dailyreport">Daily Report</a></li>
						<!--<li><a href="/automation/tcc/suspencereg">Suspence Register</a></li>-->
						<li><a href="/automation/tcc/suspenceclearreg">Suspence Clearance Register</a></li>
						<li><a href="/automation/tcc/suspencereg">Suspence Register</a></li>
						<li><a href="/automation/tcc/mainreg">Main Register</a></li>
						<li><a href="/automation/tcc/labreport">Lab Report</a></li>
						<li><a href="/automation/tcc/cashbook">CashBook</a></li>
						<li><a href="/automation/tcc/performabill">Performa Bill</a></li>
						<li><a href="/automation/tcc/nonpaymentregister">Non Payment register</a></li>
						<li><a href="/automation/tcc/tdsregister">TDS Register</a></li>
						<li><a href="/automation/tcc/clientregister">Client Register</a></li>
						<li><a href="/automation/tcc/paymentregister">Payment Register</a></li>
						<li><a href="/automation/tcc/performaregister">Performa Bill Register</a></li>
						<li><a href="/automation/tcc/registered_user">Registered Register</a></li>	
						<li><a href="/automation/tcc/consultancy">Consultancy Funds</a></li>	
						<!--<li><a href="./">Performa Bill Report</a></li>-->
						
					</ul>
				</li>
				<li><a href="/automation/report/search">Reports</a>
				<li><a href="#" class="dir">Other</a>
					<ul>
						<li><a href="/automation/tcc/payjob">Confirm Job</a></li>
						<li><a href="/automation/tcc/search_new">new search</a></li>
						<li><a href="/automation/tcc/letter">Letter</a></li>
						<!--<li><a href="/automation/tcc/map">Map</a></li>-->
						
					</ul>
				</li>
				<li><a href="#" class="dir">Suspence Clearance</a>
					<ul>
						<li><a href="/automation/tcc/tada">TA/DA Bill</a></li>
						<li><a href="/automation/tcc/suspenceclearance">Suspence Report</a></li>
						 <li><a href="/automation/tcc/transport">Transport Bill</a></li>
                          <li><a href="/automation/tcc/search_transport">Search Transport Bill</a></li>

						
					</ul>
				</li>
				<li><a href="#">Blog</a></li>
				<li><a href="/automation/tcc/contact">Contact</a></li>
			</ul>
       </div></div></div>

       
	 

        <div class="page hasShadow" id="introduction">

            
<div class="footer">

<font color="#76B900" align="center">For Bouquets & Brickbats visit :</font><br>
<a href="{{ LOCAL_URL }}/automation/tcc/contact" align="center">Credit & Feedback</a>	
        
     </div>
           {% endblock %}
		<!-- END navigation -->

		
			{% block columnwrap %}
				<div id="content-main" class="span-22 prepend-1 append-1">
				{% block content %} {% endblock %}

  				</div><!-- END content-main -->
			{% endblock %}
		<!-- END content -->

  <br/><br/><br/><br/><br/><br />
  </div>
</div>
        {% block footer %}

        {% endblock %}
   
</body>
</html>

templates/base1.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <link rel="stylesheet" href="http://localhost/style1.css" />
    <title>{% block title %}User test{% endblock %}</title>
</head>

<body>
<div id="wrapper">
	 
    <div id="header">
		<div id="headerbar">
	<div id="search">
        {% block header %}
	<a href="{{ LOCAL_URL }}/automation/tcc11_12/index/">{% trans "Home" %}</a> | 

	{% if user.is_authenticated %}
	{% trans "Logged in" %}: {{ user.username }} 
	(<a href="{% url auth_logout %}">{% trans "Log out" %}</a> | 
	<a href="{% url auth_password_change %}">{% trans "Change password" %}</a>)
	{% else %}
	<a href="{% url auth_login %}">{% trans "Log in" %}</a>
	{% endif %}
        {% endblock %}
	</div>
	<div id="logo">
		<font size="6px">TESTING AND CONSULTANCY CELL</font>
	</div>
  
  </div>
    </div>
	<div id="splash">
	<img src="http://localhost/image/aw.jpg" width="1100" height="250" alt="" />
	</div>			
    <div id="content">
        {% block content %}{% endblock %}
       </div>

				<div id="sidebar">
					<div class="post">
						<h3>IMPORTANT LINKS</h3>
						<ul class="list">
							<li class="first"><a href="#">Elementum et auctor</a></li>
							<li><a href="#">Imperdiet aliquet sapien</a></li>
													</ul>

					</div>
					<div class="post">
						<h3>Scelerisque turpis quis</h3>
						<p>
							Dignissim cugue duis posuere. Magnis mus pellentesque sollicitudin nisl libero.
						</p>
					</div>
				</div>
    
</div>
<div id="footer">
        {% block footer %}
        <hr />
        {% endblock %}
    </div>
</body>

</html>

templates/index1.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% include "home.html" %}
{% endblock %}

templates/index2.html
{% extends "base_client.html" %}
{% include 'tcc/inc/tag_cloud.html' %}
{% load i18n %}

<head>
    <title>gne</title>
</head>
{% block content %}
{% include "home.html" %}
{% endblock %}

templates/non-staff_home.html
{% extends "base_client.html" %}
{% include 'tcc/inc/tag_cloud.html' %}
{% load i18n %}

<head>
    <title>gne</title>
</head>
{% block content %}
{% include "home.html" %}
{% endblock %}

templates/staff_home.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% include "home.html" %}
{% endblock %}