report/urls.py
"""
File contains urls of the Report
"""
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic import TemplateView

"""
Urls of views.py
"""
urlpatterns = patterns('ofau.report.views',
	(r'^report/$', 'report'),
	(r'^chemical_analysis/$', 'chemical_analysis'),
	(r'^result_chem/$', 'result_chem'),
	(r'^result_cube/$', 'result_cube'),
	(r'^index/$', 'index'),
	(r'^water_test/$', 'water_test'),
	(r'^result_water/$', 'result_water'),
	(r'^brick_test/$', 'brick_test'),
	(r'^result_brick/$', 'result_brick'),
	(r'^soil_ohsr/$', 'soil_ohsr'),
	(r'^result_Soil_ohsr/$', 'result_Soil_ohsr'),
	(r'^soil_building/$', 'soil_building'),
	(r'^result_soil_building/$', 'result_soil_building'),
	(r'^admixture/$', 'admixture'),
	(r'^result_Admixture/$', 'result_Admixture'),
	(r'^cement_ppc/$', 'cement_ppc'),
	(r'^result_Cement_PPC/$', 'result_Cement_PPC'),
	(r'^cement_opc_33/$', 'cement_opc_33'),
	(r'^result_Cement_OPC_33/$', 'result_Cement_OPC_33'),
	(r'^cement_opc_43/$', 'cement_opc_43'),
	(r'^result_Cement_OPC_43/$', 'result_Cement_OPC_43'),
	(r'^cement_opc_53/$', 'cement_opc_53'),
	(r'^result_Cement_OPC_53/$', 'result_Cement_OPC_53'),
    (r'^steel/$', 'steel'),
    (r'^result_steel/$', 'result_steel'),
    (r'^concretePaver/$', 'concretePaver'),
    (r'^result_concretepaver/$', 'result_concretepaver'),
    (r'^tile/$', 'tile'),
    (r'^result_tile/$', 'result_tile'),
    (r'^pc/$', 'pc'),
    (r'^result_pc/$', 'result_pc'),
    (r'^hammer/$', 'hammer'),
    (r'^result_hammer/$', 'result_hammer'),
    (r'^groundwater/$', 'groundwater'),
    (r'^result_groundwater/$', 'result_groundwater'),
    (r'^ms_steel_plate/$', 'ms_steel_plate'),
    (r'^result_ms_Steel_plate/$', 'result_ms_Steel_plate'),
    (r'^Fe_415/$', 'Fe_415'),
    (r'^result_Fe_415/$', 'result_Fe_415'),
    (r'^Fe_500/$', 'Fe_500'),
    (r'^result_Fe_500/$', 'result_Fe_500'),
    (r'^IS_432_MS_Grade_1_a_20mm/$', 'IS_432_MS_Grade_1_a_20mm'),
    (r'^result_IS_432_MS_Grade_1_a_20mm/$', 'result_IS_432_MS_Grade_1_a_20mm'),
    (r'^is_2062_2006/$', 'is_2062_2006'),
    (r'^result_is_2062_2006/$', 'result_is_2062_2006'),
#    (r'^Soil_sample/$', 'Soil_sample'),
#    (r'^result_soil_sample/$', 'result_soil_sample'),
#    (r'^drinking_water/$', 'drinking_water'),
#    (r'^result_Drinking_water/$', 'result_Drinking_water'),


	(r'thanks$',  TemplateView, {'template': 'report/thanks.html'}),
)

"""
Urls of search.py
"""
urlpatterns += patterns('ofau.report.search',
	(r'^search_report/$', 'search_report'),
	(r'^search/$', 'search'),
	(r'^report_gen/$', 'report_gen'),
)	

"""
Urls of pdf.py
"""
urlpatterns += patterns('ofau.report.pdf',
	(r'^report_pdf/$', 'report_pdf'),
	(r'^myview/$', 'myview'),
)

reportbak/urls.py
"""
File contains urls of the Report
"""
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic.simple import direct_to_template

"""
Urls of views.py
"""
urlpatterns = patterns('ofau.report.views',
	(r'^report/$', 'report'),
	(r'^chemical_analysis/$', 'chemical_analysis'),
	(r'^result_chem/$', 'result_chem'),
	(r'^result_cube/$', 'result_cube'),
	(r'^index/$', 'index'),
	(r'^water_test/$', 'water_test'),
	(r'^result_water/$', 'result_water'),
	(r'^brick_test/$', 'brick_test'),
	(r'^result_brick/$', 'result_brick'),
	(r'^soil_ohsr/$', 'soil_ohsr'),
	(r'^result_Soil_ohsr/$', 'result_Soil_ohsr'),
	(r'^soil_building/$', 'soil_building'),
	(r'^result_soil_building/$', 'result_soil_building'),
	(r'^admixture/$', 'admixture'),
	(r'^result_Admixture/$', 'result_Admixture'),
	(r'^cement_ppc/$', 'cement_ppc'),
	(r'^result_Cement_PPC/$', 'result_Cement_PPC'),
	(r'^cement_opc_33/$', 'cement_opc_33'),
	(r'^result_Cement_OPC_33/$', 'result_Cement_OPC_33'),
	(r'^cement_opc_43/$', 'cement_opc_43'),
	(r'^result_Cement_OPC_43/$', 'result_Cement_OPC_43'),
	(r'^cement_opc_53/$', 'cement_opc_53'),
	(r'^result_Cement_OPC_53/$', 'result_Cement_OPC_53'),
        (r'^steel/$', 'steel'),
        (r'^result_steel/$', 'result_steel'),
        (r'^concretePaver/$', 'concretePaver'),
        (r'^result_concretepaver/$', 'result_concretepaver'),
        (r'^tile/$', 'tile'),
        (r'^result_tile/$', 'result_tile'),
        (r'^pc/$', 'pc'),
        (r'^result_pc/$', 'result_pc'),
        (r'^hammer/$', 'hammer'),
        (r'^result_hammer/$', 'result_hammer'),
        (r'^groundwater/$', 'groundwater'),
        (r'^result_groundwater/$', 'result_groundwater'),
	(r'thanks$',  direct_to_template, {'template': 'report/thanks.html'}),
)

"""
Urls of search.py
"""
urlpatterns += patterns('ofau.report.search',
	(r'^search_report/$', 'search_report'),
	(r'^search/$', 'search'),
	(r'^report_gen/$', 'report_gen'),
)	

"""
Urls of pdf.py
"""
urlpatterns += patterns('ofau.report.pdf',
	(r'^report_pdf/$', 'report_pdf'),
	(r'^myview/$', 'myview'),
)

src/librehatti/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from .reports.register_generator import GenerateRegister
from .reports.search import SearchResult
from ajax_select import urls as ajax_select_urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'librehatti.catalog.views.index'),
    url(r'^catalog/', include('librehatti.catalog.urls')),
    url(r'^useraccounts/', include('useraccounts.urls')),
    url(r'^print/', include('librehatti.prints.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/','librehatti.reports.views.search_form'),
    url(r'^search_result/', SearchResult.as_view()),
    url(r'^save_fields', 'librehatti.reports.views.save_fields'),
    url(r'^list_saved_registers', 'librehatti.reports.views.list_saved_registers'),
    url(r'daily_result', 'librehatti.reports.register.daily_report_result', name='daily_report_result'),
    url(r'consultancy_funds_report', 'librehatti.reports.register.consultancy_funds_report', name='consultancy_funds_report'),    
    url(r'tds_report', 'librehatti.reports.register.tds_report_result', name='tds_report_result'),    
    url(r'payment_report', 'librehatti.reports.register.payment_register', name='payment_register'),
    url(r'suspense_clearance_register', 'librehatti.reports.register.suspense_clearance_register'),
    url(r'servicetax', 'librehatti.reports.register.servicetax_register'),
    url(r'^main_register', 'librehatti.reports.register.main_register', name='main_register'),
    url(r'^proforma_register', 'librehatti.reports.register.proforma_register'),
    url(r'^non_payment_register', 'librehatti.reports.register.non_payment_register'),
    url(r'^client_register', 'librehatti.reports.register.client_register', name='client_register'),
    url(r'^material_report', 'librehatti.reports.register.material_report'),
    url(r'^lab_report', 'librehatti.reports.register.lab_report'),
    url(r'^suspense_register', 'librehatti.reports.register.suspense_register'),
    url(r'^registered_users', 'librehatti.reports.register.registered_users'),
    url(r'^filter_sub_category/', 'librehatti.reports.views.filter_sub_category'),
    url(r'^bill/', 'librehatti.prints.views.bill'),
    url(r'^suspense_bill/', 'librehatti.prints.views.suspense_bill'),
#    url(r'^quoted_bill/', 'librehatti.prints.views.quoted_bill'),
    url(r'^tax/', 'librehatti.prints.views.tax'),
    url(r'^bills/', include('librehatti.bills.urls')),
    url(r'^suspense/', include('librehatti.suspense.urls')),
    url(r'^generate_register/', GenerateRegister.as_view(), name='view_register'),
    url(r'^history/','librehatti.reports.previous_history.history'),
    url(r'^details/','librehatti.reports.previous_history.details'),
    url(r'^proforma_details/','librehatti.reports.previous_history.proforma_details'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^voucher/', include('librehatti.voucher.urls')),
    url(r'^receipt/', 'librehatti.prints.views.receipt'),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^programmeletter/', 'librehatti.programmeletter.views.programmeletter'),
    url(r'pending_clearance_register', 'librehatti.reports.register.pending_clearance_register'),
    url(r'tada_register', 'librehatti.reports.register.tada_register'),
    url(r'tada_othercharges_register', 'librehatti.reports.register.tada_othercharges_register'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urls.py
from django.conf.urls.defaults import *
from django.views.generic import TemplateView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^$', 'django.contrib.auth.views.login',
		    { 'template_name': 'index.html'}, ),
    (r'^hello', TemplateView,
                    { 'template': 'job_ok.html' }, ),
    (r'^tcc/', include('ofau.tcc.urls')),
    (r'^report/', include('ofau.report.urls')),
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    (r'^accounts/', include('registration.urls')),
   
)

tcc/forms.py
"""
%% forms.py %%

This file contain the defination of the forms of Automation Software 
"""

from django import forms
from ofau.tcc.models import *

class SuspenceClearence(forms.Form):
	"""
	**SuspenceClearance**

	Suspence Clearence Form for adding extra Charges like labour, car taxi, boring charge, etc.
	"""
	
	labour_charge = forms.IntegerField(initial= '0')
	car_taxi_charge = forms.IntegerField(initial= '0')
	boring_charge_external = forms.IntegerField(initial= '0')
	boring_charge_internal = forms.IntegerField(initial= 0)
	lab_testing_staff = forms.CharField(max_length = 20)
	field_testing_staff = forms.CharField(max_length = 20,required=False)

	test_date = forms.CharField(max_length=300,required=False)
	clear_date = forms.CharField()


class ContactForm(forms.Form):
   	subject = forms.CharField(max_length=100)
    	email = forms.EmailField( label='Your e-mail address')
    	message = forms.CharField(widget=forms.Textarea)

class MonthlyReportadd(forms.Form):
	"""
	**MonthlyReportadd**

	Monthly Reportadd Form is for getting the monthly income and taxes of the company and then subtrating the paid taxes from it.
	"""
 
	month = forms.ChoiceField(choices=MONTH_CHOICES)
	year = forms.ChoiceField(choices=YEAR_CHOICES)
	paid_service_tax =forms.IntegerField(initial= '0')
	paid_education_tax =forms.IntegerField(initial= '0')
	paid_higher_education_tax =forms.IntegerField(initial= '0')
	
class DailyReportadd(forms.Form):
	"""
	**DailyReportadd**

	Daily Report Form to retrieve Daily income Information for a specified payment type like cash, cheque, online and Demand Draft.
	"""

        start_date= forms.DateField()
        end_date= forms.DateField()
        type = forms.ChoiceField( choices=DAILY_CHOICES)

class MonthlyReport(forms.Form):
	"""
	**MonthlyReport**

	Montly Report Form to retrieve Montly Tax Information.
	"""

	month = forms.ChoiceField(choices=MONTH_CHOICES)
	year = forms.ChoiceField(choices=YEAR_CHOICES)

class DateReport(forms.Form):
	"""
	**DateReport**

	Date Report Form that displays start and end date and thus helps in retrieving data between this date range.
	"""

	start_date= forms.DateField()
        end_date= forms.DateField()

	def clean_date(self):
        	start_date = self.cleaned_data['start_date']
		end_date = self.cleaned_data['end_date']
        	if start_date > datetime.date.today():
        	    raise forms.ValidationError("The date cannot be in the future!")
        	return date

class GovPriReport(forms.Form):
	"""
	**GovPriReport**

	Governament Private Report is for different Jobs like: Government/Semi_government/Private. 
	"""

	month = forms.ChoiceField(choices=MONTH_CHOICES)
	year = forms.ChoiceField(choices=YEAR_CHOICES)
	type_of_work = models.ForeignKey(Govt)

class CashBook(forms.Form):
	"""
	**CashBook**

	Cash book to manage the money transactions within a specified date range.
	"""

        start_date= forms.DateField()
        end_date= forms.DateField()
	name = forms.CharField(max_length = 100)
	amount_given = forms.CharField(max_length = 100)


	

src/librehatti/reports/views.py
from django.shortcuts import render

from django.http import HttpResponse

from .forms import ClientForm
from .forms import OrderForm
from .forms import AddConstraints
from .forms import DailyReportForm

import simplejson

from datetime import datetime

import librehatti.settings as settings

from librehatti.catalog.request_change import request_notify
from librehatti.catalog.models import PurchaseOrder
from librehatti.catalog.models import Bill
from librehatti.catalog.models import Category

from librehatti.reports.models import SavedRegisters

from django.contrib.auth.decorators import login_required

@login_required
def search_form(request):
    """
    View to display "search.html" i.e. the search interface or form.
    
    First it'll check which type of request is i.e; 'search' request or 
    'generate register' request. On the basis of that, it'll assign code
    to search_type_code which will be used in template.

    It'll raise an exception if anyone give invalid value in 'type'.
    Argument:Http Request
    Return:Render Search
    """
    try:
        if request.GET['type'] == 'search':
            submit_url = '/search_result/'
            search_type_code = '1'
            client_form = ClientForm()
            order_form = OrderForm()
            request_status = request_notify()
            temp = {'client_form':client_form,'order_form':order_form, 
            'code':search_type_code,
            'url':submit_url,
            'request':request_status    }
        elif request.GET['type'] == 'register':
            submit_url = '/generate_register/'
            search_type_code = '2'
            client_form = ClientForm()
            order_form = OrderForm()
            add_constraints=  AddConstraints()
            request_status = request_notify()
            temp = {'client_form':client_form,'order_form':order_form, 
            'add_constraints':add_constraints,'code':search_type_code,
            'url':submit_url,
            'request':request_status    }
        else:
            return HttpResponse('<h1>Page not found</h1>')
    except:
        return HttpResponse('<h1>Invalid URL</h1>')
    return render(request, 'reports/search.html',temp)


@login_required
def save_fields(request):
    """
    Save generated register.
    Argument:Http Request
    """

    title = request.GET['title']

    if title:
        pass
    else:
        return HttpResponse('0')

    selected_fields = request.META['QUERY_STRING']

    save_fields = SavedRegisters(title = title,\
     selected_fields = selected_fields)
    save_fields.save()
    return HttpResponse('1')


@login_required
def list_saved_registers(request):
    """
    List saved registers
    Argument:Http Request
    Return:Render List of Registers
    """
    local_url = settings.LOCAL_URL
    list_of_registers = SavedRegisters.objects.\
    values('title','selected_fields')
    request_status = request_notify()
    return render(request,'reports/list_of_registers.html', \
        {'list_of_registers':list_of_registers,'local_url': local_url,\
        'request':request_status})


@login_required
def filter_sub_category(request):
    """
    This view filters the sub_category according to the parent_category.
    Argument:Http Request
    Return:Http Response
    """
    parent_category = request.GET['parent_id']
    sub_categories = Category.objects.filter(parent=parent_category)
    sub_category_dict = {}
    for sub_category in sub_categories:
        sub_category_dict[sub_category.id] = sub_category.name
    return HttpResponse(simplejson.dumps(sub_category_dict))

templates/reportbak/cement_ppc.html
{% extends "report/header.html" %}
{% load i18n %}
<html>
{% block report %}
<body>
	
	<table align="center" border="2px" cellspacing="0px">
	{% for PPC in ppc %}
		<tr>
			<th>Physical Properties</th>
			<th>IS 1489(1&2):1991(PPC)</th>
			<th>Lab Test Result</th>
		</tr>
		<tr>
			<td>Setting Time:</br>initial(Min.)<br/>final(Max.)</td>
			<td><br/>30 minites<br/>600 minutes</td>
			<td><br/>{{PPC.Initial_Time}}<br/>{{PPC.Final_Time}}</td>
		</tr>
		
		<tr>
			<td>Fineness (Blaine's air permeability method)<br/>(Min.)</td>
			<td><br/>300 m&sup2;/Kg</td>
			<td><br/>{{PPC.Fineness}}m&sup2;/Kg</td>
		</tr>
		<tr>
			<td>Soundness:</br>Le-Chat expansion<br/>Un-aerated cement(Max.)</td>
			<td><br/>10.0(Max.)<br/>5.0(Max.)</td>
			<td><br/>{{PPC.Unaerated_Cement_Le}}<br/>{{PPC.After_7_Days_Areation_Le}}</td>
		</tr>
		<tr>
			<td>Soundness:</br>Auto Clave expansion<br/>Un-aerated cement(Max.)</td>
			<td><br/>0.8(Max.)<br/>0.6(Max.)</td>
			<td><br/>{{PPC.Unaerated_Cement_Auto}}<br/>{{PPC.After_7_Days_Areation_Auto}}</td>
		</tr>
		<tr>
			<td>Consistency</td>
			<td></td>
			<td>{{PPC.Consistency}}</td>
		</tr>
		<tr>
			<td>Compressive Strength:</br>(a) 72&plusmn;1 hours (Min.)<br/>(b) 168&plusmn;2 hours (Min)<br/>(c) 672&plusmn;4 hours (Min.)</td>
			<td><br/>16 (Min)<br/>22 (Min)<br/>33 (Min.)</td>
			<td><br/>{{PPC.Hours_72}}<br/>{{PPC.Hours_168}}<br/>{{PPC.Hours_672}}</td>
		</tr>


	{% endfor  %}
	</table>
</body>
{% endblock %}
</html>

templates/reportbak/chemical_analysis.html
{% extends "report/header.html" %}
{% load i18n %}
<html>
{% block report %}
<body>
{% if chem %}

	
	
	<table align="center" border="1">
		<tr>
			<th>S.no</th>
			<th>Description</th>
			<th>Result</th>
		</tr>
	{% for chemical in chem %}
	
		<tr>
			<td>{{chemical.s_no}}</td>	
			<td>{{chemical.description}}</td>
			<td>{{chemical.result}}</td>		
		</tr>	
	{% endfor  %}
{% endif %}
	</table>
</body>
{% endblock %}
</html>

templates/reportbak/concretepaver.html
{% extends "report/header.html" %}
{% load i18n %}
<html>
{% block report %}
<body>
{% if cp %}


        <table align="center" border="1">
                <tr>
                        <th>S.No</th>
                        <th>Description</th>
                        <th>Thickness</th>
                        <th>Compressive Strength(Mpa)</th>
                </tr>
        {% for test in cp %}

                <tr>
                        <td>{{test.S_No}}</td>
                        <td>{{test.Description}}</td>
                        <td>{{test.Thickness}}</td>
                        <td>{{test.Comp_Strength_MPa}}</td>
                </tr>
        {% endfor  %}
{% endif %}
        </table>
</body>
{% endblock %}
</html>

templates/reportbak/cube.html
{% extends "report/header.html" %}
{% load i18n %}
<html>
{% block report %}
<style>

.Margin {
text-align:center;
}

</style>
<body>
{% if cubee %}

	
	<table width="100%" align="center" border="1">
		<tr>
			<th>S.No</th>
			<th>Description</th>
			<th>Breaking Load</th>
			<th>Mix</th>
			<th>Comp Strength</th>
		</tr>
	{% for test in cubee %}
	
		<tr >	
			<td class="Margin">{{test.S_No}}</td>
			<td class="Margin">{{test.Description}}</td>
			<td class="Margin">{{test.Breaking_load}}</td>	
			<td class="Margin">{{test.Mix}}</td>
			<td class="Margin">{{test.Comp_strength}}</td>		
		</tr>	
	{% endfor  %}
{% endif %}
	</table>	
</body>
{% endblock %}
</html>

templates/reportbak/hammer.html
{% extends "report/header.html" %}
{% load i18n %}
<html>
{% block report %}
<body>
{% if st %}


        <table align="center" border="1">
                <tr>
                        <th>S.No</th>
                        <th>Location</th>
                        <th>Striking Angle</th>
                        <th>Average Rebound No.</th>
                        <th>Compressive Strength(MPa)</th>
                </tr>
        {% for test in st %}

                <tr>
                        <td>{{test.S_No}}</td>
                        <td>{{test.Location}}</td>
                        <td>{{test.Striking_Angle}}</td>
                        <td>{{test.Average_Rebound_No}}</td>
                        <td>{{test.Comp_Strength_MPa}}</td>
                </tr>
        {% endfor  %}
{% endif %}
        </table>
</body>
{% endblock %}
</html>

templates/reportbak/pdf.html
{% extends "report/header.html" %}
{% load i18n %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>My Title</title>
        <style type="text/css">
            @page {
                size: {{ pagesize }};
                margin: 1cm;
                @frame footer {
                    -pdf-frame-content: footerContent;
                    bottom: 0cm;
                    margin-left: 9cm;
                    margin-right: 9cm;
                    height: 1cm;
                }
            }
        </style>
    </head>
{% block report %}
    <body>
  
{% if cubee %}

	
	<table align="center" border="1">
		<tr>
			<th>S.No</th>
			<th>Description</th>
			<th>Breaking_load</th>
			<th>Mix</th>
			<th>Comp_strength</th>
		</tr>
	{% for test in cubee %}
	
		<tr>	
			<td>{{test.S_No}}</td>
			<td>{{test.Description}}</td>
			<td>{{test.Breaking_load}}</td>	
			<td>{{test.Mix}}</td>
			<td>{{test.Comp_strength}}</td>		
		</tr>	
	{% endfor  %}
{% endif %}
	</table>	

{% endblock %}
        <div id="footerContent">
            {%block page_foot%}
                Page <pdf:pagenumber>
		 <pdf:barcode>
            {%endblock%}
        </div>
    </body>
</html>

templates/reportbak/report1.html
{% extends "base.html" %}
{% load i18n %}
<html>
<head>
    <!--	<title>GNDEC</title>	-->
</head>
{% block content %}
	<script type="text/javascript" src="add_row.js"></script>
<body>
	<h1>Report for Chemical Analysis</h1>

	{% if form.errors %}
        <p style="color: red;">
        	Please correct the error{{ form.errors|pluralize }} below.
        </p>
        {% endif %}

	<form action="" method="post">
	{% csrf_token %}
	<table id="dataTable">
		<tr>
		<td>{{ form.s_no }}</td>
		<td>{{ form.description }}</td>
		<td>{{ form.result }}</td>
		<td><INPUT type="checkbox" name="chk"/></td>
		<td>1</td>
		</tr>
	</table>
<!--	<div class="field">
        	{{ form.s_no.errors }}
        	<label for="id_subject">s_no:</label>
        	{{ form.s_no }}
        </div>
	<div class="field">
        	{{ form.description.errors }}
        	<label for="id_email">description:</label>
        	{{ form.description }}
        </div>
        <div class="field">
        	{{ form.message.result }}
        	<label for="id_message">result:</label>
        	{{ form.result }}
        </div>-->
	<INPUT type="button" value="Add Row" onclick="addRow('dataTable')" />
 
	<INPUT type="button" value="Delete Row" onclick="deleteRow('dataTable')" />	
	
        <input type="submit" value="Submit">

	</form>
</body>
</html>
{% endblock %}

templates/reportbak/report_base.html
{% extends "base.html" %}
<html>
<head>
	{% load static from static %}
	<img src="{% static "django_extensions/img/build.jpg" %}" alt="Hi!" />
</head>
{% block content %}
<body>
<table width="100%">
	<tr>
		<td><b><center><a href="{{ LOCAL_URL }}/automation/report/soil_ohsr">Soil Ohsr</a></td>
		<td><b><center><a href="{{ LOCAL_URL }}/automation/report/soil_building">Soil Building</a></td>
		<td><b><center><a href="{{ LOCAL_URL }}/automation/report/admixture">Admixture</a></td>
		<td><b><center><a href="{{ LOCAL_URL }}/automation/report/index">Cube</a></td>
	<!--	<td><b><center><a href="{{ LOCAL_URL }}/automation/report/header">header</a></td>-->
		<td><b><center><a href="{{ LOCAL_URL }}/automation/report/water_test">Water</a></td>
		<td><b><center><a href="{{ LOCAL_URL }}/automation/report/brick_test">Brick</a></td>
		<td><b><center><a href="{{ LOCAL_URL }}/automation/report/chemical_analysis">chemical_analysis</a></td>
		<td><b><center><a href="{{ LOCAL_URL }}/automation/report/cement_ppc">Cement PPC</a></td>
		<td><b><center><a href="{{ LOCAL_URL }}/automation/report/cement_opc_33">OPC 33 Grade</a></td>
		<td><b><center><a href="{{ LOCAL_URL }}/automation/report/cement_opc_43">OPC 43 Garde</a></td>
		<td><b><center><a href="{{ LOCAL_URL }}/automation/report/cement_opc_53">OPC 53 Grade</a></td>

	</tr>
</table>
</body>
</html>
{% endblock %}

templates/reportbak/steel.html
{% extends "report/header.html" %}
{% load i18n %}
<html>
{% block report %}
<body>
{% if st %}

	
	<table align="center" border="1">
		<tr>
			<th>S.No</th>
			<th>Description</th>
			<th>Acceptable Limit</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	{% for test in st %}
	
		<tr>	
			<td>{{test.S_No}}</td>
			<td>{{test.Description_of_Test}}</td>
			<td>{{test.Acceptable_limit_as_per}}</td>	
			<td>{{test.Result_1}}</td>
			<td>{{test.Result_2}}</td>
			<td>{{test.Result_3}}</td>		
		</tr>	
	{% endfor  %}
{% endif %}
	</table>	
</body>
{% endblock %}
</html>